[deps]
ConcreteStructs = "2569d6c7-a4a2-43d3-a901-331e8e4be471"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
SciMLLogging = "a6db7da4-7206-11f0-1eab-35f2a5dbe1d1"

[compat]
ConcreteStructs = "0.2.3"
Documenter = "1"
SciMLLogging = "1.7.1"
